import { ipcMain } from "electron";
import fs from "node:fs";
import path from "node:path";
import fsPromises from "node:fs/promises";
import { spawn } from "child_process";
import fg from "fast-glob";
import { getActiveProject } from "../state";

import yaml from "js-yaml";
import removeMd from 'remove-markdown'


/** Escapes a literal string for safe use inside a RegExp. */
function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Converts a ripgrep byte offset within a line to a JS string (char) index.
 * rg reports columns/offsets as UTF-8 byte offsets, but the renderer, snippet
 * builder and replace handlers all index by JS string char, so we normalise
 * everything to char offsets at the rg boundary.
 */
function byteOffsetToCharIndex(line: string, byteOffset: number): number {
  if (byteOffset <= 0) return 0;
  const buf = Buffer.from(line, "utf8");
  if (byteOffset >= buf.length) return line.length;
  return buf.subarray(0, byteOffset).toString("utf8").length;
}

interface MatchOptions {
  matchCase: boolean;
  matchWholeWord: boolean;
  useRegex: boolean;
  useMultiline?: boolean;
}

/**
 * Builds the global RegExp shared by the JS search fallback and the replace
 * handlers, so search and replace always operate on an identical set of matches.
 * Throws on an invalid pattern.
 */
function buildMatchRegex(query: string, opts: MatchOptions): RegExp {
  const rawPattern = opts.useRegex ? query : escapeRegExp(query);
  const pattern = opts.matchWholeWord ? `\\b(?:${rawPattern})\\b` : rawPattern;
  const flags = "g" + (opts.matchCase ? "" : "i") + (opts.useMultiline ? "ms" : "");
  return new RegExp(pattern, flags);
}

/** Expands $1, $2… backreferences in a regex replacement string. */
function expandReplacement(replacement: string, useRegex: boolean, captureArgs: unknown[]): string {
  if (!useRegex) return replacement;
  return replacement.replace(/\$(\d+)/g, (_full, n) => {
    const value = captureArgs[Number(n) - 1];
    return typeof value === "string" ? value : "";
  });
}

/**
 * Removes the autogenerated text from .void files
 */
function stripFrontmatter(markdown: string): string {
  // Check if the markdown starts with the frontmatter delimiter.
  if (markdown.startsWith("---")) {
    // Split on the delimiter.
    const parts = markdown.split("---");
    if (parts.length >= 3) {
      // parts[0] is empty, parts[1] is the frontmatter,
      // and parts[2] onward is the actual markdown content.
      return parts.slice(2).join("---").trimStart();
    }
  }
  return markdown;
}

/**
 * Recursively extracts visible text content from YAML object.
 * Handles nested content arrays and differentiates tables and requests.
 */
function extractContentFromYaml(node: any) {
  const result: string[] = [];
  if (!node) return result;
  // If array, traverse each item
  if (Array.isArray(node)) {
    for (const child of node) {
      result.push(...extractContentFromYaml(child));
    }
    return result;
  }
  if (typeof node === "object") {
    if (node.type === "table") {
      let rows:string[] = [];
      if(node.content){
        rows = extractContentFromYaml(node.content || []);
      } else if(node.rows){
        rows = extractContentFromYaml(node.rows || []);
      }
      result.push(rows.join("\n"));
    } else if (node.type === "tableRow") {
      const cells = extractContentFromYaml(node.content || []);
      result.push(cells.join(" "));
    } else if(node.type =='fileLink'){
      const filename:string= (node.attrs||{filename:''}).filename||''
      result.push(extractContentFromYaml(filename).join('\n'));
    } else if(node.type==='json_body'){
      const body:string= (node.attrs||{body:''}).body||''
      result.push(extractContentFromYaml(body).join('\n'));
    }else if (typeof node.content === "string") {
      result.push(node.content);
    } else if (node.content) {
      result.push(...extractContentFromYaml(node.content));
    }else if (node.row) {
      result.push(extractContentFromYaml(node.row).join(" "));
    }
  }
  if (typeof node === "string") result.push(node);
  return result;
}

/**
 * Converts markdown (with custom YAML code blocks) into human-readable text.
 */
async function extractReadableMarkdownText(markdownText: string) {
  // Strip the autogenerated part from top of the file
  markdownText = stripFrontmatter(markdownText);
  // Generate array dividing the raw content into normal text and void yaml.
  // return array of {type:text|void,content:content};
  const segments = splitTextSegmentsWithType(markdownText);
  const output = [];
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    if (seg.type === 'text' && seg.content) {
      try {
        const result = removeMd(seg.content, {
          stripListLeaders: true,
          listUnicodeChar: '',
          gfm: true,
          useImgAltText: false
        })
        output.push(result);
      } catch (e) { /* empty */ }
    } else {
      const yamlText = seg.content.trim().replace(/^void\s*/g, '').replace(/^---\s*/g, '').replace(/\s*---$/g, '');
      try {
        const parsed = yaml.load(yamlText);
        const extracted = extractContentFromYaml(parsed);
        output.push(extracted.join("\n"));
      } catch (err) {
        console.warn("YAML parse failed:", err);
      }
    }
  }
  const combined = [...output].join("\n\n");
  return combined.trim();
}

function splitTextSegmentsWithType(text: string = '') {
  const splittedItems = text.trim().split('```');
  const segments = [];
  for (let i = 0; i < splittedItems.length; i++) {
    if (splittedItems[i].startsWith('void')) {
      segments.push({
        type: 'void',
        content: splittedItems[i].replace(/^void---\s*/g, '')
          .replace(/\s*```---$/g, '')
      });
    } else {
      segments.push({ type: 'text', content: splittedItems[i] });
    }
  }
  return segments;
}


// Max results returned to the UI — prevents flooding the renderer with
// thousands of matches on broad queries and keeps the IPC payload small.
const MAX_SEARCH_RESULTS = 200;

// Reject paths that are absolute, contain `..` segments, or otherwise escape
// the project root. Used to sanitise user-supplied dirMask before it is fed
// to ripgrep/fast-glob with `cwd: projectRoot`.
function isSafeRelativePath(p: string): boolean {
  if (!p) return true;
  if (path.isAbsolute(p)) return false;
  const norm = p.replace(/\\/g, "/");
  return !norm.split("/").some((seg) => seg === "..");
}

// Semaphore for the JS fallback path — caps concurrent file reads so we
// don't spike memory by opening thousands of files simultaneously.
class ReadSemaphore {
  private slots: number;
  private queue: Array<() => void> = [];
  constructor(max: number) { this.slots = max; }
  acquire(): Promise<void> {
    if (this.slots > 0) { this.slots--; return Promise.resolve(); }
    return new Promise(resolve => this.queue.push(resolve));
  }
  release() {
    const next = this.queue.shift();
    if (next) { next(); } else { this.slots++; }
  }
}

// Track active rg processes per sender+searchId so they can be cancelled.
const activeSearches = new Map<string, { proc?: ReturnType<typeof spawn>; cancelled: boolean }>();

export function registerSearchIpcHandler() {
  const IMAGE_EXT = ["png", "jpg", "jpeg", "gif", "webp", "avif", "svg", "bmp", "ico", "tif", "tiff", "heic", "heif"];
  const ARCHIVE_EXT = ["zip", "rar", "7z", "tar", "gz", "bz2", "xz", "tgz", "tbz2", "txz"];
  const BINARY_EXT = ["exe", "msi", "dll", "bin", "iso", "img", "dmg", "so"];
  const SKIP_EXT = [...IMAGE_EXT, ...ARCHIVE_EXT, ...BINARY_EXT, "pdf"];
  const SKIP_DIR = [".git", ".idea", ".vscode"]
  const SKIP_FILES = [".DS_Store"]

  function makeSnippet(line: string, matchStartCol: number, matchLen: number, maxLen = 160): { text: string; colInPreview: number; matchLength: number } {
    // For multiline content keep newlines intact and skip truncation.
    if (line.includes("\n")) {
      return { text: line.replace(/[\r\t]/g, " "), colInPreview: matchStartCol, matchLength: matchLen };
    }
    const text = line.replace(/[\r\t]/g, " ");
    const totalLen = text.length;
    if (totalLen <= maxLen) {
      return { text, colInPreview: matchStartCol, matchLength: matchLen };
    }
    const pad = Math.max(0, Math.floor((maxLen - matchLen) / 2));
    let sliceStart = Math.max(0, matchStartCol - pad);
    let sliceEnd = Math.min(totalLen, sliceStart + maxLen);
    if (matchStartCol + matchLen > sliceEnd) {
      const needed = matchStartCol + matchLen - sliceEnd;
      sliceStart = Math.max(0, sliceStart - needed);
      sliceEnd = Math.min(totalLen, sliceStart + maxLen);
    }
    let snippet = text.slice(sliceStart, sliceEnd);
    let colInPreview = matchStartCol - sliceStart;
    if (sliceStart > 0) { snippet = "…" + snippet; colInPreview += 1; }
    if (sliceEnd < totalLen) snippet += "…";
    return { text: snippet, colInPreview, matchLength: matchLen };
  }

  // Runs `regex` over `content` and reports each match (line/col + snippet) to
  // `onMatch`, up to `limit`. Shared by the JS search fallback and searchInFile
  // so both produce identical coordinates from the same raw content.
  function forEachMatch(
    content: string,
    regex: RegExp,
    onMatch: (m: { line: number; col: number; preview: string; colInPreview: number; matchLength: number }) => void,
    limit = MAX_SEARCH_RESULTS,
  ) {
    regex.lastIndex = 0;
    let match: RegExpExecArray | null;
    let n = 0;
    while (n < limit && (match = regex.exec(content)) !== null) {
      const matchIndex = match.index;
      const matchEnd = matchIndex + match[0].length;
      const lineStart = content.lastIndexOf("\n", matchIndex - 1) + 1;
      const rawLineEnd = content.indexOf("\n", matchEnd);
      const lineEnd = rawLineEnd === -1 ? content.length : rawLineEnd;
      const lineText = content.slice(lineStart, lineEnd);
      const lineNum = content.slice(0, matchIndex).split("\n").length;
      const snippet = makeSnippet(lineText, matchIndex - lineStart, match[0].length);
      onMatch({ line: lineNum, col: (matchIndex - lineStart) + 1, preview: snippet.text, colInPreview: snippet.colInPreview, matchLength: snippet.matchLength });
      n++;
      // Prevent infinite loop on zero-length matches.
      if (match[0].length === 0) regex.lastIndex++;
    }
  }

  // Cancel a running search for a given sender+searchId key.
  ipcMain.on("search-files:cancel", (event, searchId: number) => {
    const key = `${event.sender.id}:${searchId}`;
    const state = activeSearches.get(key);
    if (state) {
      state.cancelled = true;
      state.proc?.kill();
      activeSearches.delete(key);
    }
  });

  // Streaming search: sends results one-by-one as they are found.
  ipcMain.on("search-files:start", async (event, args: { query: string; matchCase: boolean; matchWholeWord: boolean; useRegex: boolean; useMultiline: boolean; searchId: number; fileMask?: string; dirMask?: string; includeHidden?: boolean }) => {
    const { query, matchCase, matchWholeWord, useRegex, useMultiline, searchId, fileMask, dirMask, includeHidden = false } = args;
    const key = `${event.sender.id}:${searchId}`;

    const state: { proc?: ReturnType<typeof spawn>; cancelled: boolean } = { cancelled: false };
    activeSearches.set(key, state);

    const send = (result: { path: string; line: number; col: number; preview: string; colInPreview: number; matchLength: number }) => {
      if (state.cancelled || event.sender.isDestroyed()) return;
      event.sender.send("search-files:result", { searchId, result });
    };

    const done = (error?: string) => {
      activeSearches.delete(key);
      if (event.sender.isDestroyed()) return;
      event.sender.send("search-files:done", { searchId, error });
    };

    let projectRoot: string | null = null;
    try {
      projectRoot = await getActiveProject();
    } catch {
      done("No active project");
      return;
    }
    if (!projectRoot) { done("No active project"); return; }

    if (useRegex) {
      try {
        new RegExp(query);
      } catch (err) {
        done(`Invalid regular expression: ${err instanceof Error ? err.message : String(err)}`);
        return;
      }
    }

    // Drop any dirMask that would escape the project root.
    const safeDirMask = dirMask && isSafeRelativePath(dirMask) ? dirMask : undefined;

    // ── rg path ────────────────────────────────────────────────────────────────
    const rgCandidates = ["/opt/homebrew/bin/rg", "/usr/local/bin/rg", "rg"];
    const rgPath = rgCandidates.find((p) => p === "rg" || fs.existsSync(p)) ?? "rg";

    // Common rg flags shared by both output modes.
    const rgCommonArgs = ["--hidden", "--no-ignore", "--text"];
    if (!includeHidden) {
      rgCommonArgs.push("--glob", "!**/.*", "--glob", "!**/.*/**");
    }
    if (!useRegex) rgCommonArgs.push("--fixed-strings");
    for (const ext of SKIP_EXT) rgCommonArgs.push("--glob", `!**/*.${ext}`);
    for (const dir of SKIP_DIR) rgCommonArgs.push("--glob", `!**/${dir}/**`);
    for (const file of SKIP_FILES) rgCommonArgs.push("--glob", `!**/${file}`);
    if (!matchCase) rgCommonArgs.push("--ignore-case");
    if (matchWholeWord) rgCommonArgs.push("--word-regexp");
    if (fileMask) rgCommonArgs.push("--glob", fileMask);
    if (safeDirMask && /[*?{}[\]]/.test(safeDirMask)) rgCommonArgs.push("--glob", `${safeDirMask}/**`);
    rgCommonArgs.push("--", query);
    rgCommonArgs.push(safeDirMask && !/[*?{}[\]]/.test(safeDirMask) ? safeDirMask : ".");

    let count = 0;
    let rgRuntimeError: string | null = null;

    // Spawns rg with the given mode-specific args, streams stdout to `onLine`
    // one complete line at a time, and resolves on a clean exit. Records a
    // runtime error and rejects on exit code 2 so the caller can decide whether
    // to surface it or fall through to the JS fallback.
    const runRg = (modeArgs: string[], onLine: (line: string) => void) =>
      new Promise<void>((resolve, reject) => {
        const proc = spawn(rgPath, [...modeArgs, ...rgCommonArgs], { cwd: projectRoot! });
        state.proc = proc;
        let buf = "";
        let stderrBuf = "";

        proc.stdout.on("data", (d: Buffer) => {
          if (state.cancelled) return;
          buf += d.toString();
          const lines = buf.split("\n");
          buf = lines.pop() ?? "";
          for (const line of lines) {
            if (state.cancelled) return;
            if (line.trim()) onLine(line);
          }
        });

        proc.stderr.on("data", (d: Buffer) => { stderrBuf += d.toString(); });
        proc.on("error", reject);
        proc.on("close", (code) => {
          if (code === 2) { rgRuntimeError = stderrBuf.trim() || `rg exited with status ${code}`; return reject(new Error(rgRuntimeError)); }
          resolve();
        });
      });

    // ── rg --vimgrep (single-line) ────────────────────────────────────────────
    if (!useMultiline) {
      try {
        await runRg(["--vimgrep", "--with-filename", "--line-number", "--column"], (rawLine) => {
          if (count >= MAX_SEARCH_RESULTS) { state.proc?.kill(); return; }
          const colonIdx1 = rawLine.indexOf(":");
          const colonIdx2 = rawLine.indexOf(":", colonIdx1 + 1);
          const colonIdx3 = rawLine.indexOf(":", colonIdx2 + 1);
          if (colonIdx1 < 0 || colonIdx2 < 0 || colonIdx3 < 0) return;

          const file = rawLine.slice(0, colonIdx1);
          const ln = Number(rawLine.slice(colonIdx1 + 1, colonIdx2));
          const byteCol = Number(rawLine.slice(colonIdx2 + 1, colonIdx3));
          const fullLine = rawLine.slice(colonIdx3 + 1);

          // rg's column is a 1-based byte offset; normalise to a char column.
          const charStart = byteOffsetToCharIndex(fullLine, byteCol - 1);
          const absolutePath = file.startsWith(path.sep) ? file : path.join(projectRoot!, file);
          const snippet = makeSnippet(fullLine, charStart, query.length);
          send({ path: absolutePath, line: ln, col: charStart + 1, preview: snippet.text, colInPreview: snippet.colInPreview, matchLength: snippet.matchLength });
          count++;
        });
        done();
        return;
      } catch {
        if (state.cancelled) { done(); return; }
        if (rgRuntimeError) { done(rgRuntimeError); return; }
        // rg unavailable — fall through to JS fallback
      }
    }

    // ── rg --json (multiline) ─────────────────────────────────────────────────
    // JSON output gives the full matched text and exact byte offsets for every
    // match, including those that span multiple lines.
    if (useMultiline) {
      try {
        await runRg(["--json", "--multiline"], (rawLine) => {
          if (count >= MAX_SEARCH_RESULTS) { state.proc?.kill(); return; }
          try {
            const event = JSON.parse(rawLine) as { type: string; data: Record<string, unknown> };
            if (event.type !== "match") return;

            const data = event.data as {
              path?: { text?: string };
              lines?: { text?: string };
              line_number?: number;
              submatches?: Array<{ match: { text: string }; start: number; end: number }>;
            };

            const filePath = data.path?.text;
            const lineNum = data.line_number;
            const linesText = data.lines?.text ?? "";
            const submatches = data.submatches ?? [];
            if (!filePath || !lineNum || !submatches.length) return;

            const content = linesText.endsWith("\n") ? linesText.slice(0, -1) : linesText;
            const absolutePath = path.isAbsolute(filePath) ? filePath : path.join(projectRoot!, filePath);

            // Emit every submatch on this line, not just the first.
            for (const submatch of submatches) {
              if (count >= MAX_SEARCH_RESULTS) { state.proc?.kill(); break; }
              // submatch.start is a byte offset; match.text is the actual text.
              const charStart = byteOffsetToCharIndex(content, submatch.start);
              const matchLen = submatch.match.text.length;
              const snippet = makeSnippet(content, charStart, matchLen);
              send({ path: absolutePath, line: lineNum, col: charStart + 1, preview: snippet.text, colInPreview: snippet.colInPreview, matchLength: snippet.matchLength });
              count++;
            }
          } catch { /* skip malformed JSON */ }
        });
        done();
        return;
      } catch {
        if (state.cancelled) { done(); return; }
        if (rgRuntimeError) { done(rgRuntimeError); return; }
        // rg unavailable — fall through to JS fallback
      }
    }

    {

      // ── JS fallback — rg not available ───────────────────────────────────────
      let regex: RegExp;
      try {
        regex = buildMatchRegex(query, { matchCase, matchWholeWord, useRegex, useMultiline });
      } catch (err) {
        done(`Invalid regular expression: ${err instanceof Error ? err.message : String(err)}`);
        return;
      }

      const sem = new ReadSemaphore(16);
      let files: string[] = [];
      try {
        const isPlainDir = (p: string) => !!p && !/[*?{}[\]]/.test(p);
        const basePattern = isPlainDir(safeDirMask ?? "")
          ? `${safeDirMask}/${fileMask || "*.*"}`
          : fileMask
            ? (safeDirMask ? `${safeDirMask}/${fileMask}` : `**/${fileMask}`)
            : (safeDirMask ? `${safeDirMask}/**/*.*` : "**/*.*");
        files = await fg(basePattern, {
          cwd: projectRoot,
          dot: true,
          ignore: [
            ...SKIP_EXT.map((e) => `**/*.${e}`),
            ...SKIP_DIR.map((d) => `**/${d}/**`),
            ...SKIP_FILES.map((f) => `**/${f}`),
            ...(includeHidden ? [] : ["**/.*", "**/.*/**"]),
          ],
        });
      } catch {
        done();
        return;
      }

      // Process files serially so results appear in order and we can stop early.
      for (const relative of files) {
        if (state.cancelled || count >= MAX_SEARCH_RESULTS) break;
        await sem.acquire();
        try {
          if (state.cancelled || count >= MAX_SEARCH_RESULTS) break;
          const fullPath = path.join(projectRoot, relative);
          let content = "";
          try {
            content = await fsPromises.readFile(fullPath, "utf8");
            if (relative.includes(".void")) content = await extractReadableMarkdownText(content);
          } catch {
            continue;
          }
          // Find ALL matches in the file (global regex). send() is a no-op once
          // the search is cancelled, so we don't need to re-check mid-file.
          forEachMatch(content, regex, (m) => {
            send({ path: fullPath, ...m });
            count++;
          }, MAX_SEARCH_RESULTS - count);
        } finally {
          sem.release();
        }
      }

      done();
    }
  });

  ipcMain.handle("files:replaceMatch", async (_event, args: {
    path: string;
    line: number;
    col: number;
    query: string;
    replacement: string;
    matchCase: boolean;
    matchWholeWord: boolean;
    useRegex: boolean;
    useMultiline: boolean;
  }) => {
    const { path: filePath, line, col, query, replacement, matchCase, matchWholeWord, useRegex, useMultiline } = args;

    let regex: RegExp;
    try { regex = buildMatchRegex(query, { matchCase, matchWholeWord, useRegex, useMultiline }); } catch (err) {
      return { success: false, updatedPaths: [], error: `Invalid pattern: ${err instanceof Error ? err.message : String(err)}` };
    }

    try {
      const content = await fsPromises.readFile(filePath, "utf8");

      // Anchor to the clicked match by line + column rather than a file-wide
      // occurrence ordinal, so edits to other matches can't shift the target.
      let lineStart = 0;
      for (let i = 1; i < line; i++) {
        const nl = content.indexOf("\n", lineStart);
        if (nl === -1) { lineStart = content.length; break; }
        lineStart = nl + 1;
      }
      const nlAfter = content.indexOf("\n", lineStart);
      const nextLineStart = nlAfter === -1 ? content.length : nlAfter + 1;

      // Pick the match starting on that line nearest the reported column. (col
      // is a best-effort tie-breaker; usually a line has a single match.)
      regex.lastIndex = lineStart;
      let target: RegExpExecArray | null = null;
      let m: RegExpExecArray | null;
      while ((m = regex.exec(content)) !== null) {
        if (m.index >= nextLineStart) break;
        if (!target || Math.abs(m.index - lineStart - (col - 1)) < Math.abs(target.index - lineStart - (col - 1))) {
          target = m;
        }
        if (m[0].length === 0) regex.lastIndex++;
      }
      if (!target) return { success: false, updatedPaths: [] };

      const replaced = expandReplacement(replacement, useRegex, target.slice(1));
      const newContent = content.slice(0, target.index) + replaced + content.slice(target.index + target[0].length);
      if (newContent === content) return { success: false, updatedPaths: [] };
      await fsPromises.writeFile(filePath, newContent, "utf8");
      // Return the expanded text so the UI can preview $1-style replacements
      // exactly as written, not the raw template.
      return { success: true, updatedPaths: [filePath], replacement: replaced };
    } catch {
      return { success: false, updatedPaths: [], error: "File read/write failed" };
    }
  });

  // Re-scans a single file's raw content for matches. Used to refresh the
  // coordinates of the remaining matches after an in-place replace, using the
  // same regex + snippet logic as replaceMatch so the two stay consistent.
  ipcMain.handle("files:searchInFile", async (_event, args: {
    path: string;
    query: string;
    matchCase: boolean;
    matchWholeWord: boolean;
    useRegex: boolean;
    useMultiline: boolean;
  }) => {
    const { path: filePath, query, matchCase, matchWholeWord, useRegex, useMultiline } = args;
    if (!query) return { results: [] };

    let regex: RegExp;
    try { regex = buildMatchRegex(query, { matchCase, matchWholeWord, useRegex, useMultiline }); } catch { return { results: [] }; }

    let content: string;
    try { content = await fsPromises.readFile(filePath, "utf8"); } catch { return { results: [] }; }

    const results: Array<{ path: string; line: number; col: number; preview: string; colInPreview: number; matchLength: number }> = [];
    forEachMatch(content, regex, (m) => results.push({ path: filePath, ...m }));
    return { results };
  });

  ipcMain.handle("files:replaceInFiles", async (_event, args: {
    query: string;
    replacement: string;
    matchCase: boolean;
    matchWholeWord: boolean;
    useRegex: boolean;
    useMultiline: boolean;
    paths: string[];
  }) => {
    const { query, replacement, matchCase, matchWholeWord, useRegex, useMultiline, paths } = args;

    let regex: RegExp;
    try { regex = buildMatchRegex(query, { matchCase, matchWholeWord, useRegex, useMultiline }); } catch (err) {
      return { replacedCount: 0, updatedPaths: [], error: `Invalid pattern: ${err instanceof Error ? err.message : String(err)}` };
    }

    let replacedCount = 0;
    const updatedPaths: string[] = [];
    // Expanded replacement text per match, in document order, keyed by path —
    // lets the UI preview each $1-style replacement exactly as written.
    const replacements: Record<string, string[]> = {};

    for (const filePath of paths) {
      try {
        const content = await fsPromises.readFile(filePath, "utf8");
        const fileReplacements: string[] = [];
        regex.lastIndex = 0;
        const newContent = content.replace(regex, (_match, ...captureArgs) => {
          const expanded = expandReplacement(replacement, useRegex, captureArgs);
          fileReplacements.push(expanded);
          return expanded;
        });
        if (fileReplacements.length > 0 && newContent !== content) {
          await fsPromises.writeFile(filePath, newContent, "utf8");
          replacedCount += fileReplacements.length;
          updatedPaths.push(filePath);
          replacements[filePath] = fileReplacements;
        }
      } catch { /* skip unreadable files */ }
    }

    return { replacedCount, updatedPaths, replacements };
  });

  // Returns immediate child directories of the given parent (relative to the
  // active project root), excluding build/tool dirs. Parent defaults to root.
  ipcMain.handle("files:dirList", async (_event, parent?: string) => {
    let projectRoot: string | null = null;
    try { projectRoot = await getActiveProject(); } catch { return []; }
    if (!projectRoot) return [];

    const safeParent = parent && isSafeRelativePath(parent) ? parent.replace(/[/\\]+$/, "") : "";
    const absParent = safeParent ? path.join(projectRoot, safeParent) : projectRoot;
    const prefix = safeParent ? safeParent.replace(/\\/g, "/") + "/" : "";

    try {
      const entries = await fsPromises.readdir(absParent, { withFileTypes: true });
      return entries
        .filter((e) => e.isDirectory())
        .map((e) => prefix + e.name)
        .sort();
    } catch {
      return [];
    }
  });
}
